// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLrS0C6z3j1J8NkHvAJYAUdwfEDt8f-Y',
    appId: '1:821224193760:web:6320a56412d76d1e1d9a85',
    messagingSenderId: '821224193760',
    projectId: 'dsccproject-70889',
    authDomain: 'dsccproject-70889.firebaseapp.com',
    storageBucket: 'dsccproject-70889.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfNOXlxZgsiXWLt4b3FnJUAsQUjSdyWo',
    appId: '1:821224193760:android:05a21d3b71f6d0661d9a85',
    messagingSenderId: '821224193760',
    projectId: 'dsccproject-70889',
    storageBucket: 'dsccproject-70889.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ctFTBolAHIImpm47__HADgY27JTzavw',
    appId: '1:821224193760:ios:57087ea558ccff0f1d9a85',
    messagingSenderId: '821224193760',
    projectId: 'dsccproject-70889',
    storageBucket: 'dsccproject-70889.appspot.com',
    iosBundleId: 'com.example.dsccProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ctFTBolAHIImpm47__HADgY27JTzavw',
    appId: '1:821224193760:ios:1b1496f9401b3bd91d9a85',
    messagingSenderId: '821224193760',
    projectId: 'dsccproject-70889',
    storageBucket: 'dsccproject-70889.appspot.com',
    iosBundleId: 'com.example.dsccProject.RunnerTests',
  );
}
